export { generate, toRGBA } from './generate'
export type { Fingerprint } from './generate'
export type { Pattern } from './pattern'
export type { Minutia } from './minutiae'
export { ink } from './ink'
export { toSVG } from './svg'
export { compare } from './compare'
export type { Matchable } from './compare'
